server:
  port: 8085
spring:
  #datasource:
    #url: jdbc:mysql://localhost:3306/autorizacion
    #url: jdbc:mysql://localhost:33061/autorizacion
    #username: root
    #password: 4892
    #password: 123456
  jpa:
    hibernate:
      ddl-auto: update