server:
  port: 8083
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
      discovery:
        locator:
          enabled: true
      routes:
        - id: marca-service
          uri: http://mueblesstgomarca:8082/marca/ingresarmarca
          predicates:
            - Path=/marca/ingresarmarca
        - id: autorizacion-service
          uri: http://mueblesstgoautorizacion:8085
          predicates:
            - Path=/autorizacion/**
        - id: justificativo-service
          uri: http://mueblesstgojustificativo:8084
          predicates:
            - Path=/justificativo/**
        - id: planilla-service
          uri: http://mueblesstgoplanilla:8086
          predicates:
            - Path=/planilla/**

