server:
  port: 8083
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: marcas-service
          uri: http://localhost:8082/marca/cargarMarca
          predicates:
            - Path=/marca/cargarMarca
