server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tingeso
    username: root
    password: 4892
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
file:
  upload-dir: /uploads