server:
  port: 8083
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: TINGESO_EVAL2_TDISSE-1
          uri: http://localhost:8082/marca/
          predicates:
            - Path=/marca/**