server:
  port: 8083
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: TINGESO_EVAL2_CONFIG-SERVER
          uri: http://localhost:8081
          predicates:
            - Path=/